steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'shivam@instance-23'
  - '--zone'
  - 'us-central1-a'
  - '--command'
  - 'ls /home/shivam/todoapp32/main.go'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CORE_PROJECT=todoapp-402607'
options:
  logging: 'CLOUD_LOGGING_ONLY'
